---
- name: Ensure nginx config directory exists
  file:
    path: /etc/nginx
    state: directory
    mode: '0755'

- name: Deploy nginx configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: '0644'
  notify: restart nginx

- name: Deploy keepalived configuration
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    mode: '0644'
  notify: restart keepalived

- name: Start and enable services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - nginx
    - keepalived